# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "561dd49d5be871327270fe1d3308b3f0"
name = "custom-size-product-app"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"
[auth]

redirect_urls = [ "https://example.com/api/auth" ]
[access_scopes]
# write_app_proxy ekliyoruz
scopes = "write_products,read_products,read_themes,write_app_proxy"

[app_proxy]
url = "/apps" 
prefix = "apps"
subpath = "a"
